### ISSUE TITLE
Notifications Controller & Model

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/xplat#150]

**Comment by sedouard** [comment]
https://github.com/azure-storage/xplat/issues/41

**Comment by sedouard** [comment]
Gonna Reopen this for bit. Didn't get a chance to look at things till now. The PR looks good but one thing I think we are missing is a progress field. We actually [can get progress](https://github.com/Azure/azure-storage-node/blob/261f1f6c0bce2c7fd07b099ac44caab40626c1c1/lib/common/streams/speedsummary.js) from the azure storage sdk which is convent. Meaning we can display the progress of running uploads and downloads. We should have a field for that so that we can bind certain tasks with a progress component. Its a lot better than an indefinate progress indicator.

If there is no progress field then the notification (task) should just should an indefinite UI indicator until the calling client code sets it to complete/failed.
