### ISSUE TITLE
Last Modified & Size columns don't sort properly

### ISSUE THREAD

**Issue by sdavis3** [azure-storage/xplat#233]
When clicking on the Last Modified or Size column, the results don't sort properly.  In the Last Modified column, 2 months ago is incorrectly show as "more recent" than 12 days ago.  In the Size column, 1.14 MB is incorrectly shown as "smaller" than 140.27 kB.

I suspect these columns are simply performing a text-based sort which would be incorrect in this situation.

**Comment by sedouard** [comment]
Thanks for posting this @sdavis3! Looks like our ember default 'ascending/descending' sort is only doing string sorts because fields on the blob model are all string (even though we use DS.attr('number') for size, and timestamp).

Easy enough we can just add a comparison function that does the right thing.

**Comment by sedouard** [comment]
closed via https://github.com/azure-storage/xplat/pull/239
